/*
 * Nager.Date API - V3
 * Nager.Date is open source software and is completely free for commercial use. If you would like to support the project you can award a GitHub star ⭐ or even better <a href='https://github.com/sponsors/nager'>actively support us</a>
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package crystal.training.de.api.client.api;


import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import crystal.training.de.api.client.*;
import crystal.training.de.api.client.model.PublicHolidayV3Dto;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PublicHolidayApi {
    private ApiClient apiClient;

    public PublicHolidayApi() {
        this(Configuration.getDefaultApiClient());
    }

    public PublicHolidayApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for publicHolidayIsTodayPublicHoliday
     * @param countryCode  (required)
     * @param countyCode  (optional)
     * @param offset utc timezone offset (optional, default to 0)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call publicHolidayIsTodayPublicHolidayCall(String countryCode, String countyCode, Integer offset, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/api/v3/IsTodayPublicHoliday/{countryCode}"
            .replaceAll("\\{" + "countryCode" + "\\}", apiClient.escapeString(countryCode.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (countyCode != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("countyCode", countyCode));
        if (offset != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("offset", offset));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call publicHolidayIsTodayPublicHolidayValidateBeforeCall(String countryCode, String countyCode, Integer offset, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'countryCode' is set
        if (countryCode == null) {
            throw new ApiException("Missing the required parameter 'countryCode' when calling publicHolidayIsTodayPublicHoliday(Async)");
        }
        
        com.squareup.okhttp.Call call = publicHolidayIsTodayPublicHolidayCall(countryCode, countyCode, offset, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Is today a public holiday
     * The calculation is made on the basis of UTC time to adjust the time please use the offset.&lt;br /&gt;  This is a special endpoint for &#x60;curl&#x60;&lt;br /&gt;&lt;br /&gt;  200 &#x3D; Today is a public holiday&lt;br /&gt;  204 &#x3D; Today is not a public holiday&lt;br /&gt;&lt;br /&gt;  &#x60;STATUSCODE&#x3D;$(curl --silent --output /dev/stderr --write-out \&quot;%{http_code}\&quot; https://date.nager.at/Api/v2/IsTodayPublicHoliday/AT)&#x60;&lt;br /&gt;&lt;br /&gt;  &#x60;if [ $STATUSCODE -ne 200 ]; then # error handling; fi&#x60;
     * @param countryCode  (required)
     * @param countyCode  (optional)
     * @param offset utc timezone offset (optional, default to 0)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void publicHolidayIsTodayPublicHoliday(String countryCode, String countyCode, Integer offset) throws ApiException {
        publicHolidayIsTodayPublicHolidayWithHttpInfo(countryCode, countyCode, offset);
    }

    /**
     * Is today a public holiday
     * The calculation is made on the basis of UTC time to adjust the time please use the offset.&lt;br /&gt;  This is a special endpoint for &#x60;curl&#x60;&lt;br /&gt;&lt;br /&gt;  200 &#x3D; Today is a public holiday&lt;br /&gt;  204 &#x3D; Today is not a public holiday&lt;br /&gt;&lt;br /&gt;  &#x60;STATUSCODE&#x3D;$(curl --silent --output /dev/stderr --write-out \&quot;%{http_code}\&quot; https://date.nager.at/Api/v2/IsTodayPublicHoliday/AT)&#x60;&lt;br /&gt;&lt;br /&gt;  &#x60;if [ $STATUSCODE -ne 200 ]; then # error handling; fi&#x60;
     * @param countryCode  (required)
     * @param countyCode  (optional)
     * @param offset utc timezone offset (optional, default to 0)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> publicHolidayIsTodayPublicHolidayWithHttpInfo(String countryCode, String countyCode, Integer offset) throws ApiException {
        com.squareup.okhttp.Call call = publicHolidayIsTodayPublicHolidayValidateBeforeCall(countryCode, countyCode, offset, null, null);
        return apiClient.execute(call);
    }

    /**
     * Is today a public holiday (asynchronously)
     * The calculation is made on the basis of UTC time to adjust the time please use the offset.&lt;br /&gt;  This is a special endpoint for &#x60;curl&#x60;&lt;br /&gt;&lt;br /&gt;  200 &#x3D; Today is a public holiday&lt;br /&gt;  204 &#x3D; Today is not a public holiday&lt;br /&gt;&lt;br /&gt;  &#x60;STATUSCODE&#x3D;$(curl --silent --output /dev/stderr --write-out \&quot;%{http_code}\&quot; https://date.nager.at/Api/v2/IsTodayPublicHoliday/AT)&#x60;&lt;br /&gt;&lt;br /&gt;  &#x60;if [ $STATUSCODE -ne 200 ]; then # error handling; fi&#x60;
     * @param countryCode  (required)
     * @param countyCode  (optional)
     * @param offset utc timezone offset (optional, default to 0)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call publicHolidayIsTodayPublicHolidayAsync(String countryCode, String countyCode, Integer offset, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = publicHolidayIsTodayPublicHolidayValidateBeforeCall(countryCode, countyCode, offset, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
    /**
     * Build call for publicHolidayNextPublicHolidays
     * @param countryCode  (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call publicHolidayNextPublicHolidaysCall(String countryCode, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/api/v3/NextPublicHolidays/{countryCode}"
            .replaceAll("\\{" + "countryCode" + "\\}", apiClient.escapeString(countryCode.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "text/plain", "application/json", "text/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call publicHolidayNextPublicHolidaysValidateBeforeCall(String countryCode, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'countryCode' is set
        if (countryCode == null) {
            throw new ApiException("Missing the required parameter 'countryCode' when calling publicHolidayNextPublicHolidays(Async)");
        }
        
        com.squareup.okhttp.Call call = publicHolidayNextPublicHolidaysCall(countryCode, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Returns the upcoming public holidays for the next 365 days for the given country
     * 
     * @param countryCode  (required)
     * @return List&lt;PublicHolidayV3Dto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public List<PublicHolidayV3Dto> publicHolidayNextPublicHolidays(String countryCode) throws ApiException {
        ApiResponse<List<PublicHolidayV3Dto>> resp = publicHolidayNextPublicHolidaysWithHttpInfo(countryCode);
        return resp.getData();
    }

    /**
     * Returns the upcoming public holidays for the next 365 days for the given country
     * 
     * @param countryCode  (required)
     * @return ApiResponse&lt;List&lt;PublicHolidayV3Dto&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<List<PublicHolidayV3Dto>> publicHolidayNextPublicHolidaysWithHttpInfo(String countryCode) throws ApiException {
        com.squareup.okhttp.Call call = publicHolidayNextPublicHolidaysValidateBeforeCall(countryCode, null, null);
        Type localVarReturnType = new TypeToken<List<PublicHolidayV3Dto>>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Returns the upcoming public holidays for the next 365 days for the given country (asynchronously)
     * 
     * @param countryCode  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call publicHolidayNextPublicHolidaysAsync(String countryCode, final ApiCallback<List<PublicHolidayV3Dto>> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = publicHolidayNextPublicHolidaysValidateBeforeCall(countryCode, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<List<PublicHolidayV3Dto>>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for publicHolidayNextPublicHolidaysWorldwide
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call publicHolidayNextPublicHolidaysWorldwideCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/api/v3/NextPublicHolidaysWorldwide";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "text/plain", "application/json", "text/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call publicHolidayNextPublicHolidaysWorldwideValidateBeforeCall(final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        com.squareup.okhttp.Call call = publicHolidayNextPublicHolidaysWorldwideCall(progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Returns the upcoming public holidays for the next 7 days
     * 
     * @return List&lt;PublicHolidayV3Dto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public List<PublicHolidayV3Dto> publicHolidayNextPublicHolidaysWorldwide() throws ApiException {
        ApiResponse<List<PublicHolidayV3Dto>> resp = publicHolidayNextPublicHolidaysWorldwideWithHttpInfo();
        return resp.getData();
    }

    /**
     * Returns the upcoming public holidays for the next 7 days
     * 
     * @return ApiResponse&lt;List&lt;PublicHolidayV3Dto&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<List<PublicHolidayV3Dto>> publicHolidayNextPublicHolidaysWorldwideWithHttpInfo() throws ApiException {
        com.squareup.okhttp.Call call = publicHolidayNextPublicHolidaysWorldwideValidateBeforeCall(null, null);
        Type localVarReturnType = new TypeToken<List<PublicHolidayV3Dto>>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Returns the upcoming public holidays for the next 7 days (asynchronously)
     * 
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call publicHolidayNextPublicHolidaysWorldwideAsync(final ApiCallback<List<PublicHolidayV3Dto>> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = publicHolidayNextPublicHolidaysWorldwideValidateBeforeCall(progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<List<PublicHolidayV3Dto>>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for publicHolidayPublicHolidaysV3
     * @param year  (required)
     * @param countryCode  (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call publicHolidayPublicHolidaysV3Call(Integer year, String countryCode, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;
        
        // create path and map variables
        String localVarPath = "/api/v3/PublicHolidays/{year}/{countryCode}"
            .replaceAll("\\{" + "year" + "\\}", apiClient.escapeString(year.toString()))
            .replaceAll("\\{" + "countryCode" + "\\}", apiClient.escapeString(countryCode.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "text/plain", "application/json", "text/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }
    
    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call publicHolidayPublicHolidaysV3ValidateBeforeCall(Integer year, String countryCode, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        // verify the required parameter 'year' is set
        if (year == null) {
            throw new ApiException("Missing the required parameter 'year' when calling publicHolidayPublicHolidaysV3(Async)");
        }
        // verify the required parameter 'countryCode' is set
        if (countryCode == null) {
            throw new ApiException("Missing the required parameter 'countryCode' when calling publicHolidayPublicHolidaysV3(Async)");
        }
        
        com.squareup.okhttp.Call call = publicHolidayPublicHolidaysV3Call(year, countryCode, progressListener, progressRequestListener);
        return call;

        
        
        
        
    }

    /**
     * Get public holidays
     * 
     * @param year  (required)
     * @param countryCode  (required)
     * @return List&lt;PublicHolidayV3Dto&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public List<PublicHolidayV3Dto> publicHolidayPublicHolidaysV3(Integer year, String countryCode) throws ApiException {
        ApiResponse<List<PublicHolidayV3Dto>> resp = publicHolidayPublicHolidaysV3WithHttpInfo(year, countryCode);
        return resp.getData();
    }

    /**
     * Get public holidays
     * 
     * @param year  (required)
     * @param countryCode  (required)
     * @return ApiResponse&lt;List&lt;PublicHolidayV3Dto&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<List<PublicHolidayV3Dto>> publicHolidayPublicHolidaysV3WithHttpInfo(Integer year, String countryCode) throws ApiException {
        com.squareup.okhttp.Call call = publicHolidayPublicHolidaysV3ValidateBeforeCall(year, countryCode, null, null);
        Type localVarReturnType = new TypeToken<List<PublicHolidayV3Dto>>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Get public holidays (asynchronously)
     * 
     * @param year  (required)
     * @param countryCode  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call publicHolidayPublicHolidaysV3Async(Integer year, String countryCode, final ApiCallback<List<PublicHolidayV3Dto>> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = publicHolidayPublicHolidaysV3ValidateBeforeCall(year, countryCode, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<List<PublicHolidayV3Dto>>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
